-- MySQL Script generated by MySQL Workbench
-- Wed Apr 25 12:12:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_users
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_users` ;

-- -----------------------------------------------------
-- Schema db_users
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_users` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_users` ;

-- -----------------------------------------------------
-- Table `db_users`.`tbl_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_users`.`tbl_roles` (
  `id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_users`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_users`.`tbl_users` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `u_email` VARCHAR(500) NOT NULL,
  `u_password` VARCHAR(100) NOT NULL,
  `u_salt` VARCHAR(100) NOT NULL,
  `role_id` TINYINT(2) UNSIGNED NOT NULL DEFAULT 2,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_users_tbl_roles1_idx` (`role_id` ASC),
  CONSTRAINT `fk_tbl_users_tbl_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_users`.`tbl_roles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_users`.`tbl_login_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_users`.`tbl_login_info` (
  `user_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `u_login_time` INT(11) UNSIGNED NOT NULL,
  `u_persistence` VARCHAR(100) NOT NULL,
  INDEX `fk_tbl_login_info_tbl_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tbl_login_info_tbl_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_users`.`tbl_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_users`.`tbl_user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_users`.`tbl_user_details` (
  `user_id` MEDIUMINT(8) UNSIGNED NOT NULL,
  `u_name` VARCHAR(250) NOT NULL,
  `u_surname` VARCHAR(250) NOT NULL,
  `u_creation` INT(11) UNSIGNED NOT NULL,
  INDEX `fk_tbl_user_details_tbl_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_tbl_user_details_tbl_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_users`.`tbl_users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_users`.`tbl_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_users`;
INSERT INTO `db_users`.`tbl_roles` (`id`, `name`) VALUES (NULL, 'Admin');
INSERT INTO `db_users`.`tbl_roles` (`id`, `name`) VALUES (NULL, 'User');

COMMIT;

